-- ============================================================================
-- PropDeck — Stage 2 security hardening
-- ============================================================================
-- Goal: lock down projects, locations, and whatsapp_templates so the public
-- anon key can no longer write to them directly. Reads of projects/locations
-- stay public (the app's listings depend on them). All writes move behind
-- SECURITY DEFINER functions gated by the existing Stage 1 session-token
-- system (is_admin_session / validate_session), the same pattern used for
-- verify_login, admin_list_team, etc.
--
-- Safe to re-run: every statement either uses IF EXISTS/IF NOT EXISTS or
-- CREATE OR REPLACE.
-- ============================================================================


-- ── 1. Enable RLS ───────────────────────────────────────────────────────────

alter table public.projects enable row level security;
alter table public.locations enable row level security;
alter table public.whatsapp_templates enable row level security;

-- projects & locations: everyone (anon key) can still read — Home/ProjectPage/
-- Profile/AdminPanel all list them without a login-scoped session token.
drop policy if exists "public_read_projects" on public.projects;
create policy "public_read_projects" on public.projects
  for select using (true);

drop policy if exists "public_read_locations" on public.locations;
create policy "public_read_locations" on public.locations
  for select using (true);

-- No insert/update/delete policies are created for either table, and NO
-- policies at all for whatsapp_templates — with RLS enabled and no matching
-- policy, PostgREST (the anon key) is denied by default. Writes only happen
-- through the SECURITY DEFINER functions below, which run as the table
-- owner and therefore bypass RLS entirely.


-- ── 2. Admin-only project functions ─────────────────────────────────────────

-- Insert (p_id is null) or update (p_id set) a project from the same payload
-- object AdminPanel.tsx already builds in save(). jsonb_populate_record maps
-- JSON keys onto the `projects` row shape; the explicit column list below
-- means id / created_at / persona_pitches can never be clobbered by the
-- payload even if the client stuffed extra keys into it.
create or replace function public.admin_save_project(
  p_token text,
  p_id uuid,
  p_payload jsonb
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  if not is_admin_session(p_token) then
    raise exception 'Not authorized';
  end if;

  if p_id is null then
    insert into projects (
      name, developer, location, area, rera_number, status, possession_date,
      price_min, price_max, carpet_area_min, carpet_area_max,
      bhk_types, unit_configs, usps, landmarks,
      pitch_script, image_url, google_maps_url, tags
    )
    select
      r.name, r.developer, r.location, r.area, r.rera_number, r.status, r.possession_date,
      r.price_min, r.price_max, r.carpet_area_min, r.carpet_area_max,
      r.bhk_types, r.unit_configs, r.usps, r.landmarks,
      r.pitch_script, r.image_url, r.google_maps_url, r.tags
    from jsonb_populate_record(null::projects, p_payload) r
    returning id into v_id;
  else
    update projects p
    set
      name = r.name, developer = r.developer, location = r.location, area = r.area,
      rera_number = r.rera_number, status = r.status, possession_date = r.possession_date,
      price_min = r.price_min, price_max = r.price_max,
      carpet_area_min = r.carpet_area_min, carpet_area_max = r.carpet_area_max,
      bhk_types = r.bhk_types, unit_configs = r.unit_configs, usps = r.usps,
      landmarks = r.landmarks,
      pitch_script = r.pitch_script, image_url = r.image_url,
      google_maps_url = r.google_maps_url, tags = r.tags
    from jsonb_populate_record(null::projects, p_payload) r
    where p.id = p_id
    returning p.id into v_id;
  end if;

  return v_id;
end;
$$;

-- Persona pitches are generated by Gemini AFTER the project row already
-- exists (save() inserts/updates first, then writes persona_pitches once the
-- AI call returns), so this is a separate, narrow update function.
create or replace function public.admin_update_project_personas(
  p_token text,
  p_id uuid,
  p_personas jsonb
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not is_admin_session(p_token) then
    raise exception 'Not authorized';
  end if;

  update projects set persona_pitches = p_personas where id = p_id;
end;
$$;

create or replace function public.admin_delete_project(
  p_token text,
  p_id uuid
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not is_admin_session(p_token) then
    raise exception 'Not authorized';
  end if;

  delete from projects where id = p_id;
end;
$$;


-- ── 3. Admin-only location functions ────────────────────────────────────────

create or replace function public.admin_add_location(
  p_token text,
  p_name text
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not is_admin_session(p_token) then
    raise exception 'Not authorized';
  end if;

  insert into locations (name) values (p_name);
end;
$$;

create or replace function public.admin_delete_location(
  p_token text,
  p_id bigint
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text;
  v_count int;
begin
  if not is_admin_session(p_token) then
    raise exception 'Not authorized';
  end if;

  select name into v_name from locations where id = p_id;

  -- AdminPanel.tsx already blocks this client-side using its in-memory
  -- location counts, but re-check server-side too so a location a project
  -- still points at can never be deleted regardless of caller.
  select count(*) into v_count from projects where location = v_name;
  if v_count > 0 then
    raise exception 'Cannot delete "%": % project(s) use this location', v_name, v_count;
  end if;

  delete from locations where id = p_id;
end;
$$;


-- ── 4. Per-salesperson whatsapp_templates functions ─────────────────────────
-- whatsapp_templates has no public policies at all (see step 1), so these
-- two functions are now the ONLY way to read or write it. Each resolves the
-- caller's own salesperson id from the session token via validate_session —
-- callers can never pass someone else's id in.

create or replace function public.get_my_whatsapp_templates(
  p_token text
) returns table (project_id uuid, message text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_salesperson_id uuid;
begin
  select id into v_salesperson_id from validate_session(p_token);
  if v_salesperson_id is null then
    raise exception 'Not authorized';
  end if;

  return query
    select w.project_id, w.message
    from whatsapp_templates w
    where w.salesperson_id = v_salesperson_id;
end;
$$;

create or replace function public.save_my_whatsapp_template(
  p_token text,
  p_project_id uuid,
  p_message text
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_salesperson_id uuid;
begin
  select id into v_salesperson_id from validate_session(p_token);
  if v_salesperson_id is null then
    raise exception 'Not authorized';
  end if;

  insert into whatsapp_templates (salesperson_id, project_id, message)
  values (v_salesperson_id, p_project_id, p_message)
  on conflict (salesperson_id, project_id) do update set message = excluded.message;
end;
$$;
